In [1]:
import numpy as np

In [56]:
def forward_rnn(x, U, W, V):
    h_dim = 4
    h_layer = np.zeros((h_dim, h_dim))
    print(x.shape[1])
    for i in range(x.shape[1]):
        print(x[:,i])
        U_T = np.transpose(U)
        x_T = np.transpose(x[:,i])
        W_T = np.transpose(W)
        h_layer_T = np.transpose(h_layer)
        print(U_T.shape)
        print(x_T.shape)
        print(W_T.shape)
        print(h_layer_T.shape)
        h_layer = np.tanh(U_T @ x_T + W_T @ h_layer_T)
        y = V @ h_layer
        #print(y)
    #print(h_layer)
    #for i in range(x.shape[1]):


In [60]:

np.random.seed(42)
x = np.array([[[1, 2, 3, 4 ], [2, 3, 4, 4], [3, 4, 5, 4]]])
U = np.random.rand(4, 4)
print(U)
W = np.random.rand(4, x.shape[2])
print(W)
V = np.random.rand(2, 4)
print(V)
forward_rnn(x, U, W, V)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]
[[0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]]
[[0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]
3
[[1 2 3 4]]
(4, 4)
(4, 1)
(4, 4)
(4, 4)
[[2 3 4 4]]
(4, 4)
(4, 1)
(4, 4)
(4, 4)
[[3 4 5 4]]
(4, 4)
(4, 1)
(4, 4)
(4, 4)
